package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/agentizen/agent-sdk-go/pkg/agent"
	"github.com/agentizen/agent-sdk-go/pkg/model/providers/openai"
	"github.com/agentizen/agent-sdk-go/pkg/network"
	"github.com/agentizen/agent-sdk-go/pkg/runner"
)

// Custom Orchestrator Network example
//
// Demonstrates how to supply your own orchestrator agent to fully control
// how the user prompt is decomposed into sub-tasks and how the results
// are synthesised into a final answer. This is useful when the built-in
// orchestrator's generic instructions are not sufficient for your domain.

func main() {
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		log.Fatal("OPENAI_API_KEY environment variable is required")
	}

	provider := openai.NewProvider(apiKey)
	provider.SetDefaultModel("gpt-4.1-mini")

	// --- Custom orchestrator ---
	// The orchestrator uses domain-specific instructions to decompose and synthesise.
	customOrchestrator := agent.NewAgent("MarketingOrchestrator").
		WithModel("gpt-4.1-mini").
		SetSystemInstructions(`You are the orchestrating agent for a market analysis workflow.

You operate in two modes:

DECOMPOSITION MODE — When the input does NOT start with "RESULTS:":
Analyse the user's market analysis request and assign a specific research sub-task
to each of the two agents: "Researcher" and "Strategist".
Respond ONLY with valid JSON, no markdown:
{"Researcher": "<data gathering task>", "Strategist": "<strategic analysis task>"}

SYNTHESIS MODE — When the input starts with "RESULTS:":
Read the findings from both agents and produce a professional, executive-style
market analysis report with sections: Executive Summary, Key Findings, and Recommendations.`)

	// --- Specialised agents ---
	researcher := agent.NewAgent("Researcher").
		WithModel("gpt-4.1-mini").
		SetSystemInstructions("You gather market data, statistics, and factual information. Be precise and cite specific figures when possible.")

	strategist := agent.NewAgent("Strategist").
		WithModel("gpt-4.1-mini").
		SetSystemInstructions("You provide strategic analysis and competitive insights. Focus on opportunities, threats, and actionable recommendations.")

	// Build the network with the custom orchestrator.
	cfg := network.NewNetworkConfig().
		WithAgents(
			network.AgentSlot{Agent: researcher, Role: "Market data researcher", SubTaskHint: "Gather statistics and market data"},
			network.AgentSlot{Agent: strategist, Role: "Strategic analyst", SubTaskHint: "Analyse strategy and competition"},
		).
		WithStrategy(network.StrategyParallel).
		WithOrchestrator(customOrchestrator) // Override the built-in orchestrator.

	base := runner.NewRunner().WithDefaultProvider(provider)
	nr := network.NewNetworkRunner(base)

	prompt := "Analyse the cloud computing market for a startup targeting SMB customers"

	fmt.Printf("Running custom-orchestrated network on: %q\n\n", prompt)

	opts := &runner.RunOptions{
		Input:    prompt,
		MaxTurns: 5,
		RunConfig: &runner.RunConfig{
			Model:         "gpt-4.1-mini",
			ModelProvider: provider,
		},
	}

	result, err := nr.RunNetwork(context.Background(), cfg, opts)
	if err != nil {
		log.Fatalf("Network run failed: %v", err)
	}

	fmt.Println("=== Agent Contributions ===")
	for _, ar := range result.AgentResults {
		fmt.Printf("\n[%s]\n", ar.AgentName)
		if ar.Error != nil {
			fmt.Printf("  ERROR: %v\n", ar.Error)
		} else if ar.RunResult != nil {
			fmt.Printf("  %v\n", ar.RunResult.FinalOutput)
		}
	}

	fmt.Println("\n=== Executive Market Analysis Report ===")
	fmt.Println(result.FinalOutput)

	// You can also access the orchestrator's own run result from the synthesis step.
	if result.OrchestratorResult != nil {
		fmt.Printf("\n(Report generated by: %s)\n", result.LastAgent.Name)
	}
}
