package main

import (
	"fmt"
	"math"
	"strconv"
)

const generatedFileHeader = "// Code generated by scripts/sync-model-registry. DO NOT EDIT.\n\n"

func formatFloat(value float64) string {
	if value == math.Trunc(value) {
		return fmt.Sprintf("%.1f", value)
	}
	return strconv.FormatFloat(value, 'f', -1, 64)
}
