package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
	"github.com/citizenofai/agent-sdk-go/pkg/model"
)

type capabilitySet struct {
	vision    bool
	documents bool
}

type pricingSet struct {
	inputCost  float64
	outputCost float64
	found      bool
}

type capabilityModelUpdate struct {
	modelID string
	caps    capabilitySet
}

type capabilityProviderUpdate struct {
	providerID string
	models     []capabilityModelUpdate
}

type capabilityUpdates struct {
	providers []capabilityProviderUpdate
}

type pricingModelUpdate struct {
	modelID string
	pricing pricingSet
}

type pricingProviderUpdate struct {
	providerID string
	models     []pricingModelUpdate
}

type pricingUpdates struct {
	providers []pricingProviderUpdate
}

type capabilityProviderSource struct {
	providerID string
	prefixes   []string
	allow      func(string) bool
	infer      func(string) capabilitySet
}

type pricingProviderSource struct {
	providerID string
	prefixes   []string
	allow      func(string) bool
}

type normalizeRules struct {
	allowNoDigitAliases map[string]struct{}
	rejectNoiseTokens   bool
}

type corpusOptions struct {
	includeLinks bool
}

var (
	spaceRegexp = regexp.MustCompile(`\s+`)

	generatedFileHeader = "// Code generated by scripts/sync-model-registry. DO NOT EDIT.\n\n"

	pricePattern = regexp.MustCompile(`\$\s*([0-9]+(?:\.[0-9]+)?)`)

	capabilitySectionRegexps = map[string]*regexp.Regexp{
		"mistral":   regexp.MustCompile(`(?ms)(\t"mistral": \{\n)(.*?)(\t\},\n)`),
		"openai":    regexp.MustCompile(`(?ms)(\t"openai": \{\n)(.*?)(\t\},\n)`),
		"anthropic": regexp.MustCompile(`(?ms)(\t"anthropic": \{\n)(.*?)(\t\},\n)`),
		"gemini":    regexp.MustCompile(`(?ms)(\t"gemini": \{\n)(.*?)(\t\},\n)`),
	}

	pricingSectionRegexps = map[string]*regexp.Regexp{
		"anthropic": regexp.MustCompile(`(?ms)(\t"anthropic": \{\n)(.*?)(\t\},\n)`),
		"gemini":    regexp.MustCompile(`(?ms)(\t"gemini": \{\n)(.*?)(\t\},\n)`),
		"mistral":   regexp.MustCompile(`(?ms)(\t"mistral": \{\n)(.*?)(\t\},\n)`),
		"openai":    regexp.MustCompile(`(?ms)(\t"openai": \{\n)(.*?)(\t\},\n)`),
	}

	capabilityEntryRegexp = regexp.MustCompile(`\{prefix: "([^"]+)", caps: map\[Capability\]bool\{([^}]*)\}\},`)
	pricingEntryRegexp    = regexp.MustCompile(`"([^"]+)":\s*\{InputCostPerMillion:\s*([0-9.]+),\s*OutputCostPerMillion:\s*([0-9.]+)\}`)
)

var capabilitySources = []capabilityProviderSource{
	{
		providerID: "mistral",
		prefixes: []string{
			"mistral-",
			"magistral-",
			"ministral-",
			"pixtral",
			"ocr-3",
		},
		allow: allowMistralCapabilityID,
		infer: inferCapabilitiesMistral,
	},
	{
		providerID: "openai",
		prefixes: []string{
			"gpt-",
			"o1",
			"o3",
			"o4",
		},
		allow: allowOpenAICapabilityID,
		infer: inferCapabilitiesOpenAI,
	},
	{
		providerID: "anthropic",
		prefixes: []string{
			"claude-",
		},
		allow: allowAnthropicCapabilityID,
		infer: inferCapabilitiesAnthropic,
	},
	{
		providerID: "gemini",
		prefixes: []string{
			"gemini-",
		},
		allow: allowGeminiCapabilityID,
		infer: inferCapabilitiesGemini,
	},
}

var pricingSources = []pricingProviderSource{
	{
		providerID: "anthropic",
		prefixes: []string{
			"claude-",
		},
		allow: allowAnthropicPricingID,
	},
	{
		providerID: "gemini",
		prefixes: []string{
			"gemini-",
		},
		allow: allowGeminiPricingID,
	},
	{
		providerID: "mistral",
		prefixes: []string{
			"mistral-large-",
			"mistral-medium-",
			"mistral-small-",
			"magistral-small-",
			"magistral-medium-",
			"ministral-3b-",
			"ministral-8b-",
			"ministral-14b-",
		},
		allow: allowMistralPricingID,
	},
	{
		providerID: "openai",
		prefixes: []string{
			"gpt-",
			"o1",
			"o3",
			"o4",
		},
		allow: allowOpenAIPricingID,
	},
}

var knownNoDigitModelAliases = map[string]struct{}{
	"claude-haiku-latest":  {},
	"claude-opus-latest":   {},
	"claude-sonnet-latest": {},
	"gemini-flash-latest":  {},
	"gemini-pro-latest":    {},
	"pixtral":              {},
}

func main() {
	capabilitiesPath := flag.String("capabilities", "pkg/model/capabilities.go", "Path to capabilities.go")
	pricingPath := flag.String("pricing", "pkg/model/pricing.go", "Path to pricing.go")
	timeoutSec := flag.Int("timeout", 30, "HTTP timeout in seconds")
	writeChanges := flag.Bool("write", false, "Write changes to output files (default: report only)")
	verbose := flag.Bool("verbose", false, "Print discovered model updates per provider")
	flag.Parse()

	if err := run(*capabilitiesPath, *pricingPath, *timeoutSec, *writeChanges, *verbose); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

func run(capabilitiesPath, pricingPath string, timeoutSec int, writeChanges, verbose bool) error {
	capsFileBytes, err := os.ReadFile(capabilitiesPath)
	if err != nil {
		return fmt.Errorf("read capabilities file: %w", err)
	}
	pricingFileBytes, err := os.ReadFile(pricingPath)
	if err != nil {
		return fmt.Errorf("read pricing file: %w", err)
	}

	httpClient := &http.Client{Timeout: timeDurationSeconds(timeoutSec)}

	capUpdates, err := collectCapabilityUpdates(httpClient)
	if err != nil {
		return err
	}
	priceUpdates, err := collectPricingUpdates(httpClient)
	if err != nil {
		return err
	}

	if !hasNewCapabilityUpdates(capUpdates) && !hasNewPricingUpdates(priceUpdates) {
		fmt.Println("model registry files are already aligned with official provider docs")
		return nil
	}

	reportCapabilityUpdates(capUpdates, verbose)
	reportPricingUpdates(priceUpdates, verbose)

	if !writeChanges {
		fmt.Println("report-only mode: re-run with -write to update registry files")
		return nil
	}

	updatedCapabilities, err := applyCapabilityUpdates(string(capsFileBytes), capUpdates)
	if err != nil {
		return fmt.Errorf("update capabilities file content: %w", err)
	}
	updatedCapabilities = ensureGeneratedHeader(updatedCapabilities)
	if err := os.WriteFile(capabilitiesPath, []byte(updatedCapabilities), 0644); err != nil {
		return fmt.Errorf("write capabilities file: %w", err)
	}

	updatedPricing, err := applyPricingUpdates(string(pricingFileBytes), priceUpdates)
	if err != nil {
		return fmt.Errorf("update pricing file content: %w", err)
	}
	updatedPricing = ensureGeneratedHeader(updatedPricing)
	if err := os.WriteFile(pricingPath, []byte(updatedPricing), 0644); err != nil {
		return fmt.Errorf("write pricing file: %w", err)
	}

	fmt.Println("updated capabilities.go and pricing.go from official provider sources")
	return nil
}

func collectCapabilityUpdates(client *http.Client) (capabilityUpdates, error) {
	collector := newCapabilityCollector()
	for _, src := range capabilitySources {
		sourceURL, ok := model.OfficialProviderModelDocsURL(src.providerID)
		if !ok || strings.TrimSpace(sourceURL) == "" {
			return capabilityUpdates{}, fmt.Errorf("missing official docs URL for provider: %s", src.providerID)
		}

		content, err := fetchProviderModelsCorpus(client, src.providerID, sourceURL)
		if err != nil {
			return capabilityUpdates{}, fmt.Errorf("fetch %s models page failed: %w", src.providerID, err)
		}

		modelIDs := extractModelIDs(content, src.prefixes, src.allow, normalizeRules{
			allowNoDigitAliases: knownNoDigitModelAliases,
			rejectNoiseTokens:   true,
		})
		for _, modelID := range modelIDs {
			if model.ProviderSupports(src.providerID, modelID, model.CapabilityVision) ||
				model.ProviderSupports(src.providerID, modelID, model.CapabilityDocuments) {
				continue
			}
			inferred := src.infer(modelID)
			if !inferred.vision && !inferred.documents {
				continue
			}
			collector.add(src.providerID, modelID, inferred)
		}
	}
	return collector.finalize(), nil
}

func collectPricingUpdates(client *http.Client) (pricingUpdates, error) {
	collector := newPricingCollector()

	type providerFetcher struct {
		id      string
		extract func(*http.Client, string) (map[string]pricingSet, error)
	}
	fetchers := []providerFetcher{
		{"openai", extractOpenAIPricing},
		{"anthropic", extractAnthropicPricing},
		{"gemini", extractGeminiPricing},
		{"mistral", extractMistralPricing},
	}

	for _, f := range fetchers {
		collector.touch(f.id)

		pricingURL, ok := model.OfficialProviderPricingURL(f.id)
		if !ok || strings.TrimSpace(pricingURL) == "" {
			return pricingUpdates{}, fmt.Errorf("missing pricing URL for provider: %s", f.id)
		}

		scraped, err := f.extract(client, pricingURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: skip pricing sync for provider=%s: %v\n", f.id, err)
			continue
		}

		for modelID, ps := range scraped {
			collector.add(f.id, modelID, ps)
		}
	}
	return collector.finalize(), nil
}

func hasNewCapabilityUpdates(updates capabilityUpdates) bool {
	for _, provider := range updates.providers {
		if len(provider.models) > 0 {
			return true
		}
	}
	return false
}

func hasNewPricingUpdates(updates pricingUpdates) bool {
	for _, provider := range updates.providers {
		if len(provider.models) > 0 {
			return true
		}
	}
	return false
}

func fetchProviderPricingCorpus(client *http.Client, providerID, primaryURL string) (string, error) {
	urls := pricingURLCandidates(providerID, primaryURL)
	var errs []string
	for _, url := range urls {
		content, err := fetchDocumentCorpus(client, url, "agent-sdk-go-model-registry-sync/1.0", corpusOptions{})
		if err == nil {
			return content, nil
		}
		errs = append(errs, fmt.Sprintf("%s (%v)", url, err))
	}
	return "", fmt.Errorf("all pricing URL candidates failed: %s", strings.Join(errs, "; "))
}

func fetchProviderModelsCorpus(client *http.Client, providerID, primaryURL string) (string, error) {
	urls := modelURLCandidates(providerID, primaryURL)
	var errs []string
	for _, candidateURL := range urls {
		if providerID == "openai" {
			content, err := fetchOpenAIModelsCorpus(client, candidateURL)
			if err == nil {
				return content, nil
			}
			errs = append(errs, fmt.Sprintf("%s (%v)", candidateURL, err))
			continue
		}

		content, err := fetchDocumentCorpus(client, candidateURL, "agent-sdk-go-model-registry-sync/1.0", corpusOptions{includeLinks: true})
		if err == nil {
			return content, nil
		}
		errs = append(errs, fmt.Sprintf("%s (%v)", candidateURL, err))
	}
	return "", fmt.Errorf("all models URL candidates failed: %s", strings.Join(errs, "; "))
}

func fetchOpenAIModelsCorpus(client *http.Client, entryURL string) (string, error) {
	body, err := fetchDocumentRaw(client, entryURL, "agent-sdk-go-model-registry-sync/1.0")
	if err != nil {
		return "", err
	}

	corpus, links, err := extractDocumentCorpusAndLinks(body, corpusOptions{includeLinks: true})
	if err != nil {
		return "", err
	}

	modelLinks := filterOpenAIModelLinks(entryURL, links)
	if len(modelLinks) == 0 {
		return corpus, nil
	}

	var b strings.Builder
	b.WriteString(corpus)
	b.WriteString(" ")

	maxPages := 20
	for i, link := range modelLinks {
		if i >= maxPages {
			break
		}
		subCorpus, fetchErr := fetchDocumentCorpus(client, link, "agent-sdk-go-model-registry-sync/1.0", corpusOptions{})
		if fetchErr != nil {
			continue
		}
		b.WriteString(subCorpus)
		b.WriteString(" ")
	}

	return spaceRegexp.ReplaceAllString(strings.ToLower(b.String()), " "), nil
}

func filterOpenAIModelLinks(baseURL string, hrefs []string) []string {
	resolved := map[string]struct{}{}
	out := make([]string, 0, len(hrefs))
	for _, href := range hrefs {
		abs, err := resolveAbsoluteURL(baseURL, href)
		if err != nil {
			continue
		}
		u, err := url.Parse(abs)
		if err != nil {
			continue
		}
		u.Fragment = ""
		if !strings.EqualFold(u.Host, "developers.openai.com") {
			continue
		}
		if !strings.HasPrefix(u.Path, "/api/docs/models") {
			continue
		}
		canonical := u.String()
		if _, ok := resolved[canonical]; ok {
			continue
		}
		resolved[canonical] = struct{}{}
		out = append(out, canonical)
	}
	sort.Strings(out)
	return out
}

func pricingURLCandidates(providerID, primaryURL string) []string {
	urls := []string{primaryURL}
	if providerID == "openai" {
		urls = append(urls,
			"https://developers.openai.com/api/docs/pricing",
		)
	}
	seen := map[string]struct{}{}
	out := make([]string, 0, len(urls))
	for _, url := range urls {
		trimmed := strings.TrimSpace(url)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		out = append(out, trimmed)
	}
	return out
}

func modelURLCandidates(providerID, primaryURL string) []string {
	urls := []string{primaryURL}
	if providerID == "openai" {
		urls = append(urls,
			"https://developers.openai.com/api/docs/models",
			"https://developers.openai.com/api/docs/models/",
		)
	}

	seen := map[string]struct{}{}
	out := make([]string, 0, len(urls))
	for _, rawURL := range urls {
		trimmed := strings.TrimSpace(rawURL)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		out = append(out, trimmed)
	}
	return out
}

func reportCapabilityUpdates(updates capabilityUpdates, verbose bool) {
	for _, provider := range updates.providers {
		fmt.Printf("capabilities provider=%s new_models=%d\n", provider.providerID, len(provider.models))
		if !verbose {
			continue
		}
		for _, m := range provider.models {
			fmt.Printf("  - %s\n", m.modelID)
		}
	}
}

func reportPricingUpdates(updates pricingUpdates, verbose bool) {
	for _, provider := range updates.providers {
		fmt.Printf("pricing provider=%s new_models=%d\n", provider.providerID, len(provider.models))
		if !verbose {
			continue
		}
		for _, m := range provider.models {
			if m.pricing.found {
				fmt.Printf("  + %s (in=$%.4f/MTok out=$%.4f/MTok)\n", m.modelID, m.pricing.inputCost, m.pricing.outputCost)
				continue
			}
			fmt.Printf("  + %s (prices not parsed - manual review required)\n", m.modelID)
		}
	}
}

func fetchDocumentCorpus(client *http.Client, sourceURL, userAgent string, opts corpusOptions) (string, error) {
	body, err := fetchDocumentRaw(client, sourceURL, userAgent)
	if err != nil {
		return "", err
	}
	return extractDocumentCorpus(body, opts)
}

func fetchDocumentRaw(client *http.Client, sourceURL, userAgent string) ([]byte, error) {
	req, err := http.NewRequest(http.MethodGet, sourceURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", userAgent)
	req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	req.Header.Set("Cache-Control", "no-cache")
	req.Header.Set("Pragma", "no-cache")

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("unexpected status: %d", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return body, nil
}

func extractDocumentCorpus(raw []byte, opts corpusOptions) (string, error) {
	corpus, _, err := extractDocumentCorpusAndLinks(raw, opts)
	return corpus, err
}

func extractDocumentCorpusAndLinks(raw []byte, opts corpusOptions) (string, []string, error) {
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(raw))
	if err != nil {
		return "", nil, err
	}

	var b strings.Builder
	links := make([]string, 0)
	body := doc.Find("body")
	if body.Length() == 0 {
		body = doc.Selection
	}

	b.WriteString(body.Text())
	b.WriteString(" ")

	body.Find("code, pre, kbd, samp, td, th").Each(func(_ int, s *goquery.Selection) {
		b.WriteString(s.Text())
		b.WriteString(" ")
	})

	if opts.includeLinks {
		body.Find("a").Each(func(_ int, s *goquery.Selection) {
			if href, ok := s.Attr("href"); ok {
				b.WriteString(href)
				b.WriteString(" ")
				links = append(links, href)
			}
		})
	}

	lower := strings.ToLower(b.String())
	return spaceRegexp.ReplaceAllString(lower, " "), links, nil
}

func resolveAbsoluteURL(baseURL, ref string) (string, error) {
	base, err := url.Parse(baseURL)
	if err != nil {
		return "", err
	}
	rel, err := url.Parse(strings.TrimSpace(ref))
	if err != nil {
		return "", err
	}
	return base.ResolveReference(rel).String(), nil
}

func extractModelIDs(content string, prefixes []string, allowFn func(string) bool, rules normalizeRules) []string {
	set := map[string]struct{}{}
	for _, token := range strings.Fields(content) {
		candidate := normalizeModelID(token, rules)
		if candidate == "" {
			continue
		}
		if !hasAnyPrefix(candidate, prefixes) {
			continue
		}
		if !allowFn(candidate) {
			continue
		}
		set[candidate] = struct{}{}
	}

	out := make([]string, 0, len(set))
	for id := range set {
		out = append(out, id)
	}
	sort.Strings(out)
	return out
}

func hasAnyPrefix(value string, prefixes []string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(value, prefix) {
			return true
		}
	}
	return false
}

func allowMistralCapabilityID(modelID string) bool {
	if modelID == "pixtral" {
		return true
	}
	if strings.HasPrefix(modelID, "ocr-3") {
		return true
	}
	return hasAnyPrefix(modelID, []string{
		"mistral-large-",
		"mistral-medium-",
		"mistral-small-",
		"mistral-ocr-",
		"magistral-small-",
		"magistral-medium-",
		"ministral-3b-",
		"ministral-8b-",
		"ministral-14b-",
		"pixtral-",
	})
}

func allowOpenAICapabilityID(modelID string) bool {
	if hasAnyPrefix(modelID, []string{"o1", "o3", "o4"}) {
		return true
	}
	return hasAnyPrefix(modelID, []string{
		"gpt-4o",
		"gpt-4.1",
		"gpt-4.5",
		"gpt-5",
		"gpt-4-turbo",
		"gpt-4-vision",
	})
}

func allowAnthropicCapabilityID(modelID string) bool {
	if !strings.HasPrefix(modelID, "claude-") {
		return false
	}
	return strings.Contains(modelID, "opus") ||
		strings.Contains(modelID, "sonnet") ||
		strings.Contains(modelID, "haiku") ||
		strings.HasPrefix(modelID, "claude-3")
}

func allowGeminiCapabilityID(modelID string) bool {
	if !strings.HasPrefix(modelID, "gemini-") {
		return false
	}
	if modelID == "gemini-flash-latest" || modelID == "gemini-pro-latest" {
		return true
	}
	return containsDigit(modelID)
}

func allowMistralPricingID(modelID string) bool {
	return hasAnyPrefix(modelID, []string{
		"mistral-large-",
		"mistral-medium-",
		"mistral-small-",
		"magistral-small-",
		"magistral-medium-",
		"ministral-3b-",
		"ministral-8b-",
		"ministral-14b-",
	})
}

func allowOpenAIPricingID(modelID string) bool {
	if hasAnyPrefix(modelID, []string{"o1", "o3", "o4"}) {
		return true
	}
	return strings.HasPrefix(modelID, "gpt-")
}

func allowAnthropicPricingID(modelID string) bool {
	if !strings.HasPrefix(modelID, "claude-") {
		return false
	}
	return strings.Contains(modelID, "opus") ||
		strings.Contains(modelID, "sonnet") ||
		strings.Contains(modelID, "haiku")
}

func allowGeminiPricingID(modelID string) bool {
	return strings.HasPrefix(modelID, "gemini-") && containsDigit(modelID)
}

func normalizeModelID(modelID string, rules normalizeRules) string {
	trimmed := strings.TrimSpace(strings.ToLower(modelID))
	trimmed = strings.Trim(trimmed, "\"'`),.;:!?[]{}<>")
	if trimmed == "" {
		return ""
	}
	if strings.Contains(trimmed, "/") || strings.Contains(trimmed, " ") {
		return ""
	}
	if strings.HasPrefix(trimmed, "http") {
		return ""
	}
	if len(trimmed) > 96 {
		return ""
	}
	if !containsDigit(trimmed) {
		if _, ok := rules.allowNoDigitAliases[trimmed]; !ok {
			return ""
		}
	}
	if !isTokenCharsetValid(trimmed) {
		return ""
	}
	if rules.rejectNoiseTokens && hasAnyNoiseToken(trimmed) {
		return ""
	}
	return trimmed
}

func containsDigit(s string) bool {
	for _, r := range s {
		if r >= '0' && r <= '9' {
			return true
		}
	}
	return false
}

func isTokenCharsetValid(s string) bool {
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == '.' {
			continue
		}
		return false
	}
	return true
}

func hasAnyNoiseToken(s string) bool {
	noise := []string{
		"logo", "card", "color", "font", "table", "grid", "cta", "supported",
		"resource", "theme", "bullet", "description", "overview", "button",
		"not-supported", "experimental", "icon", "javascript", "react", "tailwind",
	}
	for _, token := range noise {
		if strings.Contains(s, token) {
			return true
		}
	}
	return false
}

func timeDurationSeconds(sec int) time.Duration {
	if sec <= 0 {
		sec = 30
	}
	return time.Duration(sec) * time.Second
}

func inferCapabilitiesMistral(modelID string) capabilitySet {
	m := strings.ToLower(modelID)
	if strings.HasPrefix(m, "mistral-ocr") || strings.HasPrefix(m, "ocr-3") {
		return capabilitySet{documents: true}
	}
	if strings.HasPrefix(m, "mistral-large") ||
		strings.HasPrefix(m, "mistral-medium") ||
		strings.HasPrefix(m, "mistral-small") ||
		strings.HasPrefix(m, "magistral-") ||
		strings.HasPrefix(m, "ministral-") ||
		strings.HasPrefix(m, "pixtral-") ||
		m == "pixtral" {
		return capabilitySet{vision: true}
	}
	return capabilitySet{}
}

func inferCapabilitiesOpenAI(modelID string) capabilitySet {
	m := strings.ToLower(modelID)
	if strings.HasPrefix(m, "gpt-4") || strings.HasPrefix(m, "gpt-5") {
		return capabilitySet{vision: true, documents: true}
	}
	if strings.HasPrefix(m, "o1") || strings.HasPrefix(m, "o3") || strings.HasPrefix(m, "o4") {
		return capabilitySet{vision: true}
	}
	return capabilitySet{}
}

func inferCapabilitiesAnthropic(modelID string) capabilitySet {
	if strings.HasPrefix(strings.ToLower(modelID), "claude-") {
		return capabilitySet{vision: true, documents: true}
	}
	return capabilitySet{}
}

func inferCapabilitiesGemini(modelID string) capabilitySet {
	m := strings.ToLower(modelID)
	if strings.HasPrefix(m, "gemini-1.5") ||
		strings.HasPrefix(m, "gemini-2") ||
		strings.HasPrefix(m, "gemini-3") ||
		m == "gemini-flash-latest" ||
		m == "gemini-pro-latest" {
		return capabilitySet{vision: true, documents: true}
	}
	return capabilitySet{}
}

// extractOpenAIPricing parses https://developers.openai.com/api/docs/pricing.
// The page has multiple HTML tables; we target tables whose header row contains
// Model, Input, and Output columns, skipping fine-tuning tables (have Training
// column) and non-token-priced rows (prices that contain "/").
func extractOpenAIPricing(client *http.Client, pageURL string) (map[string]pricingSet, error) {
	body, err := fetchDocumentRaw(client, pageURL, "agent-sdk-go-model-registry-sync/1.0")
	if err != nil {
		return nil, err
	}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(body))
	if err != nil {
		return nil, err
	}

	out := map[string]pricingSet{}
	priorityByModel := map[string]int{}
	doc.Find("table").Each(func(_ int, tbl *goquery.Selection) {
		// Find the row that actually defines columns (the first row can be grouped colspans).
		var headers []string
		tbl.Find("tr").EachWithBreak(func(_ int, tr *goquery.Selection) bool {
			candidate := make([]string, 0)
			tr.Find("th,td").Each(func(_ int, c *goquery.Selection) {
				candidate = append(candidate, strings.ToLower(strings.TrimSpace(c.Text())))
			})
			for _, h := range candidate {
				if h == "model" {
					headers = candidate
					return false
				}
			}
			return true
		})
		if len(headers) == 0 {
			return
		}

		// Must have Model, Input, Output columns; must NOT have Training column.
		modelCol, inputCol, outputCol := -1, -1, -1
		hasTraining := false
		for i, h := range headers {
			switch {
			case h == "model":
				modelCol = i
			case strings.Contains(h, "input") && !strings.Contains(h, "cached"):
				if inputCol < 0 {
					inputCol = i
				}
			case h == "output":
				if outputCol < 0 {
					outputCol = i
				}
			case strings.Contains(h, "training"):
				hasTraining = true
			}
		}
		if hasTraining || modelCol < 0 || inputCol < 0 || outputCol < 0 {
			return
		}

		tablePriority := 0
		if pane := tbl.Closest("[data-content-switcher-pane]"); pane.Length() > 0 {
			switch strings.ToLower(strings.TrimSpace(pane.AttrOr("data-value", ""))) {
			case "standard":
				tablePriority = 2
			case "batch":
				tablePriority = 1
			}
		}

		tbl.Find("tr").Each(func(r int, row *goquery.Selection) {
			_ = r
			if row.Find("th").Length() > 0 {
				return
			}
			cells := row.Find("td")
			if cells.Length() <= outputCol {
				return
			}
			rawModel := strings.ToLower(strings.Join(strings.Fields(cells.Eq(modelCol).Text()), " "))
			modelID := strings.TrimSpace(strings.Split(rawModel, " ")[0])
			inputText := strings.TrimSpace(cells.Eq(inputCol).Text())
			outputText := strings.TrimSpace(cells.Eq(outputCol).Text())

			// Skip non-token-priced rows (e.g. "/ hour", "/ minute").
			if strings.Contains(inputText, "/") || strings.Contains(outputText, "/") {
				return
			}

			inCost := parseDollarAmount(inputText)
			outCost := parseDollarAmount(outputText)
			if inCost <= 0 && outCost <= 0 {
				return
			}
			if !allowOpenAIPricingID(modelID) {
				return
			}
			if prevPriority, exists := priorityByModel[modelID]; !exists || tablePriority > prevPriority {
				out[modelID] = pricingSet{inputCost: inCost, outputCost: outCost, found: true}
				priorityByModel[modelID] = tablePriority
			}
		})
	})
	return out, nil
}

// extractAnthropicPricing parses https://docs.anthropic.com/en/docs/about-claude/models.
// The page has a single feature table. We find the "Claude API ID" row for model
// identifiers and the "Pricing" row for costs formatted as "$X / input MTok$Y / output MTok".
func extractAnthropicPricing(client *http.Client, pageURL string) (map[string]pricingSet, error) {
	body, err := fetchDocumentRaw(client, pageURL, "agent-sdk-go-model-registry-sync/1.0")
	if err != nil {
		return nil, err
	}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(body))
	if err != nil {
		return nil, err
	}

	out := map[string]pricingSet{}
	doc.Find("table").Each(func(_ int, tbl *goquery.Selection) {
		var modelIDs []string
		var pricingCells []string

		tbl.Find("tr").Each(func(_ int, row *goquery.Selection) {
			cells := row.Find("th,td")
			label := strings.ToLower(strings.TrimSpace(cells.First().Text()))
			switch {
			case strings.Contains(label, "api id") || strings.Contains(label, "api alias"):
				cells.Each(func(i int, td *goquery.Selection) {
					if i == 0 {
						return
					}
					modelIDs = append(modelIDs, strings.TrimSpace(td.Text()))
				})
			case label == "pricing" || strings.Contains(label, "pricing"):
				cells.Each(func(i int, td *goquery.Selection) {
					if i == 0 {
						return
					}
					pricingCells = append(pricingCells, strings.TrimSpace(td.Text()))
				})
			}
		})

		if len(modelIDs) == 0 || len(pricingCells) == 0 {
			return
		}
		for i, modelID := range modelIDs {
			if i >= len(pricingCells) {
				break
			}
			if !allowAnthropicPricingID(modelID) {
				continue
			}
			in, outCost := parseAnthropicPricingCell(pricingCells[i])
			if in <= 0 && outCost <= 0 {
				continue
			}
			if _, exists := out[modelID]; !exists {
				out[modelID] = pricingSet{inputCost: in, outputCost: outCost, found: true}
			}
		}
	})
	return out, nil
}

// parseAnthropicPricingCell parses cells like "$5 / input MTok$25 / output MTok".
func parseAnthropicPricingCell(cell string) (in, out float64) {
	matches := pricePattern.FindAllStringSubmatch(cell, -1)
	if len(matches) >= 1 {
		in, _ = strconv.ParseFloat(matches[0][1], 64)
	}
	if len(matches) >= 2 {
		out, _ = strconv.ParseFloat(matches[1][1], 64)
	}
	return
}

// extractGeminiPricing parses https://ai.google.dev/gemini-api/docs/pricing.
// The page uses <h2 id="gemini-*"> headings to identify models, each followed
// by a "Standard" section with a 3-column table [category | free | paid].
// We pick the first table after each h2 that has "Input price"/"Output price" rows.
func extractGeminiPricing(client *http.Client, pageURL string) (map[string]pricingSet, error) {
	body, err := fetchDocumentRaw(client, pageURL, "agent-sdk-go-model-registry-sync/1.0")
	if err != nil {
		return nil, err
	}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(body))
	if err != nil {
		return nil, err
	}

	out := map[string]pricingSet{}

	// Walk through all h2 elements whose id starts with "gemini-".
	doc.Find("h2[id]").Each(func(_ int, h2 *goquery.Selection) {
		id, _ := h2.Attr("id")
		if !strings.HasPrefix(id, "gemini-") {
			return
		}
		modelID := id

		// Find the first <table> after this h2 that contains "Input price" rows.
		// We search siblings and descendants until the next h2.
		var ps pricingSet
		h2.NextUntil("h2").Find("table").EachWithBreak(func(_ int, tbl *goquery.Selection) bool {
			var inCost, outCost float64
			tbl.Find("tr").Each(func(_ int, row *goquery.Selection) {
				cells := row.Find("th,td")
				label := strings.ToLower(strings.Join(strings.Fields(cells.First().Text()), " "))
				// Paid tier is col[2]; col[0]=label, col[1]=free tier.
				paidCell := strings.TrimSpace(cells.Eq(2).Text())
				switch {
				case strings.HasPrefix(label, "input price"):
					inCost = parseDollarAmount(paidCell)
				case strings.HasPrefix(label, "output price"):
					outCost = parseDollarAmount(paidCell)
				}
			})
			if inCost > 0 || outCost > 0 {
				ps = pricingSet{inputCost: inCost, outputCost: outCost, found: true}
				return false // stop at first valid table (Standard, not Batch)
			}
			return true
		})

		if ps.found && allowGeminiPricingID(modelID) {
			if _, exists := out[modelID]; !exists {
				out[modelID] = ps
			}
		}
	})
	return out, nil
}

// extractMistralPricing parses https://mistral.ai/pricing.
// The page embeds JSON fragments in script tags with the pattern:
//
//	"<modelAlias>","price":[{"value":"Input (/M tokens)","price_dollar":"$$N.NN",...},...]
//
// Alias-to-versioned-ID mapping is performed so registry keys stay consistent.
func extractMistralPricing(client *http.Client, pageURL string) (map[string]pricingSet, error) {
	body, err := fetchDocumentRaw(client, pageURL, "agent-sdk-go-model-registry-sync/1.0")
	if err != nil {
		return nil, err
	}

	// Pattern: <alias>","price":[{..."Input..."price_dollar":"$$N"...},{..."Output..."price_dollar":"$$N"...}]
	// We match the alias and then the two price_dollar values that follow.
	aliasRe := regexp.MustCompile(`"((?:mistral|magistral|ministral|pixtral|codestral|devstral)[a-z0-9_-]*)","price":\[`)
	priceRe := regexp.MustCompile(`"price_dollar":"(\$?\$?[\d.]+)"`)

	raw := string(body)
	out := map[string]pricingSet{}

	for _, loc := range aliasRe.FindAllStringIndex(raw, -1) {
		m := aliasRe.FindStringSubmatch(raw[loc[0]:loc[1]])
		if len(m) < 2 {
			continue
		}
		alias := m[1]

		// Extract up to 2 price_dollar values in the next 400 chars.
		window := raw[loc[1]:min(loc[1]+400, len(raw))]
		priceMatches := priceRe.FindAllStringSubmatch(window, 2)
		if len(priceMatches) < 2 {
			continue
		}
		inStr := strings.TrimLeft(priceMatches[0][1], "$")
		outStr := strings.TrimLeft(priceMatches[1][1], "$")
		inCost, err1 := strconv.ParseFloat(inStr, 64)
		outCost, err2 := strconv.ParseFloat(outStr, 64)
		if err1 != nil || err2 != nil || (inCost == 0 && outCost == 0) {
			continue
		}

		// Map alias to versioned ID; fall back to alias if not mapped.
		modelID := mistralAliasToVersioned(alias)
		if !allowMistralPricingID(modelID) {
			continue
		}
		if _, exists := out[modelID]; !exists {
			out[modelID] = pricingSet{inputCost: inCost, outputCost: outCost, found: true}
		}
	}
	return out, nil
}

// mistralAliasToVersioned maps Mistral *-latest aliases to their current versioned
// API IDs. When Mistral ships a new version, update the mapping and run the sync.
// Aliases not in this table are passed through unchanged.
func mistralAliasToVersioned(alias string) string {
	const table = `
		mistral-large-latest     mistral-large-2512
		mistral-medium-latest    mistral-medium-2508
		mistral-small-latest     mistral-small-2506
		magistral-medium-latest  magistral-medium-2509
		magistral-small-latest   magistral-small-2509
		ministral-8b-latest      ministral-8b-2512
		ministral-3b-latest      ministral-3b-2410
	`
	for _, line := range strings.Split(table, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == alias {
			return fields[1]
		}
	}
	return alias
}

// parseDollarAmount extracts the first decimal number following a "$" sign.
// Returns 0 if no valid price is found.
func parseDollarAmount(s string) float64 {
	m := pricePattern.FindStringSubmatch(s)
	if len(m) < 2 {
		return 0
	}
	v, err := strconv.ParseFloat(m[1], 64)
	if err != nil {
		return 0
	}
	return v
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
func applyCapabilityUpdates(content string, updates capabilityUpdates) (string, error) {
	updated := content
	for _, providerID := range []string{"mistral", "openai", "anthropic", "gemini"} {
		re, ok := capabilitySectionRegexps[providerID]
		if !ok {
			return "", fmt.Errorf("missing section regexp for provider: %s", providerID)
		}
		match := re.FindStringSubmatch(updated)
		if len(match) != 4 {
			return "", fmt.Errorf("provider section not found in capabilities.go: %s", providerID)
		}

		existing := parseCapabilityEntries(match[2])
		for _, provider := range updates.providers {
			if provider.providerID != providerID {
				continue
			}
			for _, model := range provider.models {
				existing[model.modelID] = model.caps
			}
		}

		rewrittenBody := renderSortedCapabilityEntries(existing)
		replacement := match[1] + rewrittenBody + match[3]
		updated = strings.Replace(updated, match[0], replacement, 1)
	}
	return updated, nil
}

func parseCapabilityEntries(sectionBody string) map[string]capabilitySet {
	entries := map[string]capabilitySet{}
	matches := capabilityEntryRegexp.FindAllStringSubmatch(sectionBody, -1)
	for _, m := range matches {
		if len(m) != 3 {
			continue
		}
		capsText := m[2]
		entries[m[1]] = capabilitySet{
			vision:    strings.Contains(capsText, "CapabilityVision: true"),
			documents: strings.Contains(capsText, "CapabilityDocuments: true"),
		}
	}
	return entries
}

func renderSortedCapabilityEntries(entries map[string]capabilitySet) string {
	prefixes := make([]string, 0, len(entries))
	for prefix := range entries {
		prefixes = append(prefixes, prefix)
	}
	sort.Strings(prefixes)

	var b strings.Builder
	for _, prefix := range prefixes {
		caps := entries[prefix]
		b.WriteString("\t\t{prefix: ")
		fmt.Fprintf(&b, "%q", prefix)
		b.WriteString(", caps: map[Capability]bool{")
		if caps.vision {
			b.WriteString("CapabilityVision: true")
			if caps.documents {
				b.WriteString(", ")
			}
		}
		if caps.documents {
			b.WriteString("CapabilityDocuments: true")
		}
		b.WriteString("}},\n")
	}
	return b.String()
}

func applyPricingUpdates(content string, updates pricingUpdates) (string, error) {
	updated := content
	scrapedByProvider := map[string]map[string]pricingSet{}
	for _, provider := range updates.providers {
		entries := map[string]pricingSet{}
		for _, model := range provider.models {
			entries[model.modelID] = model.pricing
		}
		scrapedByProvider[provider.providerID] = entries
	}

	for _, providerID := range []string{"anthropic", "gemini", "mistral", "openai"} {
		re, ok := pricingSectionRegexps[providerID]
		if !ok {
			return "", fmt.Errorf("missing section regexp for provider: %s", providerID)
		}
		match := re.FindStringSubmatch(updated)
		if len(match) != 4 {
			return "", fmt.Errorf("provider section not found in pricing.go: %s", providerID)
		}

		existing := parsePricingEntries(match[2])
		if scraped, ok := scrapedByProvider[providerID]; ok && len(scraped) > 0 {
			existing = scraped
		}

		rewrittenBody := renderSortedPricingEntries(providerID, existing)
		replacement := match[1] + rewrittenBody + match[3]
		updated = strings.Replace(updated, match[0], replacement, 1)
	}
	return updated, nil
}

func parsePricingEntries(sectionBody string) map[string]pricingSet {
	entries := map[string]pricingSet{}
	matches := pricingEntryRegexp.FindAllStringSubmatch(sectionBody, -1)
	for _, m := range matches {
		if len(m) == 4 {
			in, _ := strconv.ParseFloat(m[2], 64)
			out, _ := strconv.ParseFloat(m[3], 64)
			entries[m[1]] = pricingSet{inputCost: in, outputCost: out, found: in != 0 || out != 0}
		}
	}
	return entries
}

func renderSortedPricingEntries(providerID string, entries map[string]pricingSet) string {
	modelIDs := make([]string, 0, len(entries))
	for id := range entries {
		modelIDs = append(modelIDs, id)
	}
	sort.Strings(modelIDs)

	var b strings.Builder
	for _, modelID := range modelIDs {
		ps := entries[modelID]
		if ps.inputCost == 0 && ps.outputCost == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf(
			"\t\t%q: {InputCostPerMillion: %s, OutputCostPerMillion: %s},\n",
			modelID,
			formatFloat(ps.inputCost),
			formatFloat(ps.outputCost),
		))
	}
	return b.String()
}

func formatFloat(f float64) string {
	if f == math.Trunc(f) {
		return fmt.Sprintf("%.1f", f)
	}
	return strconv.FormatFloat(f, 'f', -1, 64)
}

func ensureGeneratedHeader(content string) string {
	if strings.HasPrefix(content, generatedFileHeader) {
		return content
	}
	return generatedFileHeader + content
}

type capabilityCollector struct {
	providers map[string]map[string]capabilitySet
}

func newCapabilityCollector() *capabilityCollector {
	return &capabilityCollector{providers: map[string]map[string]capabilitySet{}}
}

func (c *capabilityCollector) add(providerID, modelID string, caps capabilitySet) {
	if _, ok := c.providers[providerID]; !ok {
		c.providers[providerID] = map[string]capabilitySet{}
	}
	c.providers[providerID][modelID] = caps
}

func (c *capabilityCollector) finalize() capabilityUpdates {
	providerIDs := make([]string, 0, len(c.providers))
	for providerID := range c.providers {
		providerIDs = append(providerIDs, providerID)
	}
	sort.Strings(providerIDs)

	out := capabilityUpdates{providers: make([]capabilityProviderUpdate, 0, len(providerIDs))}
	for _, providerID := range providerIDs {
		models := c.providers[providerID]
		modelIDs := make([]string, 0, len(models))
		for modelID := range models {
			modelIDs = append(modelIDs, modelID)
		}
		sort.Strings(modelIDs)

		providerUpdate := capabilityProviderUpdate{
			providerID: providerID,
			models:     make([]capabilityModelUpdate, 0, len(modelIDs)),
		}
		for _, modelID := range modelIDs {
			providerUpdate.models = append(providerUpdate.models, capabilityModelUpdate{
				modelID: modelID,
				caps:    models[modelID],
			})
		}
		out.providers = append(out.providers, providerUpdate)
	}
	return out
}

type pricingCollector struct {
	providers map[string]map[string]pricingSet
}

func newPricingCollector() *pricingCollector {
	return &pricingCollector{providers: map[string]map[string]pricingSet{}}
}

func (c *pricingCollector) touch(providerID string) {
	if _, ok := c.providers[providerID]; ok {
		return
	}
	c.providers[providerID] = map[string]pricingSet{}
}

func (c *pricingCollector) add(providerID, modelID string, pricing pricingSet) {
	if _, ok := c.providers[providerID]; !ok {
		c.providers[providerID] = map[string]pricingSet{}
	}
	c.providers[providerID][modelID] = pricing
}

func (c *pricingCollector) finalize() pricingUpdates {
	providerIDs := make([]string, 0, len(c.providers))
	for providerID := range c.providers {
		providerIDs = append(providerIDs, providerID)
	}
	sort.Strings(providerIDs)

	out := pricingUpdates{providers: make([]pricingProviderUpdate, 0, len(providerIDs))}
	for _, providerID := range providerIDs {
		models := c.providers[providerID]
		modelIDs := make([]string, 0, len(models))
		for modelID := range models {
			modelIDs = append(modelIDs, modelID)
		}
		sort.Strings(modelIDs)

		providerUpdate := pricingProviderUpdate{
			providerID: providerID,
			models:     make([]pricingModelUpdate, 0, len(modelIDs)),
		}
		for _, modelID := range modelIDs {
			providerUpdate.models = append(providerUpdate.models, pricingModelUpdate{
				modelID: modelID,
				pricing: models[modelID],
			})
		}
		out.providers = append(out.providers, providerUpdate)
	}
	return out
}
