// Code generated by scripts/sync-model-registry. DO NOT EDIT.

package model

import "strings"

type Capability string

const (
	CapabilityAudioGeneration  Capability = "audioGeneration"
	CapabilityBatchAPI         Capability = "batchAPI"
	CapabilityCaching          Capability = "caching"
	CapabilityCodeExecution    Capability = "codeExecution"
	CapabilityDocuments        Capability = "documents"
	CapabilityFileSearch       Capability = "fileSearch"
	CapabilityFunctionCalling  Capability = "functionCalling"
	CapabilityImageGeneration  Capability = "imageGeneration"
	CapabilityLiveAPI          Capability = "liveAPI"
	CapabilityStructuredOutput Capability = "structuredOutput"
	CapabilityThinking         Capability = "thinking"
	CapabilityVision           Capability = "vision"
)

type ModelCapabilitySet struct {
	AudioGeneration  bool
	BatchAPI         bool
	Caching          bool
	CodeExecution    bool
	Documents        bool
	FileSearch       bool
	FunctionCalling  bool
	ImageGeneration  bool
	LiveAPI          bool
	StructuredOutput bool
	Thinking         bool
	Vision           bool
}

func CapabilitiesFor(provider, modelID string) ModelCapabilitySet {
	return ModelCapabilitySet{
		AudioGeneration:  ProviderSupports(provider, modelID, CapabilityAudioGeneration),
		BatchAPI:         ProviderSupports(provider, modelID, CapabilityBatchAPI),
		Caching:          ProviderSupports(provider, modelID, CapabilityCaching),
		CodeExecution:    ProviderSupports(provider, modelID, CapabilityCodeExecution),
		Documents:        ProviderSupports(provider, modelID, CapabilityDocuments),
		FileSearch:       ProviderSupports(provider, modelID, CapabilityFileSearch),
		FunctionCalling:  ProviderSupports(provider, modelID, CapabilityFunctionCalling),
		ImageGeneration:  ProviderSupports(provider, modelID, CapabilityImageGeneration),
		LiveAPI:          ProviderSupports(provider, modelID, CapabilityLiveAPI),
		StructuredOutput: ProviderSupports(provider, modelID, CapabilityStructuredOutput),
		Thinking:         ProviderSupports(provider, modelID, CapabilityThinking),
		Vision:           ProviderSupports(provider, modelID, CapabilityVision),
	}
}

type capabilityEntry struct {
	prefix string
	caps   map[Capability]bool
}

var providerCapabilities = map[string][]capabilityEntry{
	"anthropic": {
		{prefix: "claude-haiku-4-5-20251001", caps: map[Capability]bool{CapabilityDocuments: true, CapabilityVision: true}},
		{prefix: "claude-opus-4-6", caps: map[Capability]bool{CapabilityDocuments: true, CapabilityVision: true}},
		{prefix: "claude-sonnet-4-6", caps: map[Capability]bool{CapabilityDocuments: true, CapabilityVision: true}},
	},
	"gemini": {
		{prefix: "gemini-2.5-flash", caps: map[Capability]bool{CapabilityBatchAPI: true, CapabilityCaching: true, CapabilityCodeExecution: true, CapabilityFileSearch: true, CapabilityFunctionCalling: true, CapabilityStructuredOutput: true, CapabilityThinking: true}},
		{prefix: "gemini-2.5-flash-lite", caps: map[Capability]bool{CapabilityBatchAPI: true, CapabilityCaching: true, CapabilityCodeExecution: true, CapabilityFileSearch: true, CapabilityFunctionCalling: true, CapabilityStructuredOutput: true, CapabilityThinking: true}},
		{prefix: "gemini-2.5-pro", caps: map[Capability]bool{CapabilityBatchAPI: true, CapabilityCaching: true, CapabilityCodeExecution: true, CapabilityFileSearch: true, CapabilityFunctionCalling: true, CapabilityStructuredOutput: true, CapabilityThinking: true}},
	},
	"lmstudio": {},
	"mistral": {
		{prefix: "magistral-medium-2509", caps: map[Capability]bool{CapabilityThinking: true, CapabilityVision: true}},
		{prefix: "magistral-small-2509", caps: map[Capability]bool{CapabilityThinking: true, CapabilityVision: true}},
		{prefix: "ministral-14b-2512", caps: map[Capability]bool{CapabilityVision: true}},
		{prefix: "ministral-3b-2512", caps: map[Capability]bool{CapabilityVision: true}},
		{prefix: "ministral-8b-2512", caps: map[Capability]bool{CapabilityVision: true}},
		{prefix: "mistral-large-2512", caps: map[Capability]bool{CapabilityVision: true}},
		{prefix: "mistral-medium-2508", caps: map[Capability]bool{CapabilityVision: true}},
		{prefix: "mistral-ocr-2512", caps: map[Capability]bool{CapabilityDocuments: true}},
		{prefix: "mistral-small-2603", caps: map[Capability]bool{CapabilityVision: true}},
	},
	"openai": {
		{prefix: "gpt-5.4-2026-03-05", caps: map[Capability]bool{CapabilityThinking: true, CapabilityVision: true}},
		{prefix: "gpt-5.4-mini-2026-03-17", caps: map[Capability]bool{CapabilityThinking: true, CapabilityVision: true}},
		{prefix: "gpt-5.4-nano-2026-03-17", caps: map[Capability]bool{CapabilityThinking: true, CapabilityVision: true}},
		{prefix: "gpt-5.4-pro-2026-03-05", caps: map[Capability]bool{CapabilityThinking: true, CapabilityVision: true}},
	},
}

func ProviderSupports(provider, modelID string, cap Capability) bool {
	entries, ok := providerCapabilities[strings.ToLower(provider)]
	if !ok {
		return false
	}
	lowerModelID := strings.ToLower(modelID)
	for _, entry := range entries {
		if strings.HasPrefix(lowerModelID, entry.prefix) {
			return entry.caps[cap]
		}
	}
	return false
}
