// Code generated by scripts/sync-model-registry. DO NOT EDIT.

package model

import "sort"

type ModelMetadata struct {
	DisplayName     string
	Description     string
	ReleaseDate     string
	ContextWindow   int
	MaxOutputTokens int
}

func GetModelMetadata(provider, modelID string) (ModelMetadata, bool) {
	models, ok := modelMetadata[provider]
	if !ok {
		return ModelMetadata{}, false
	}
	meta, ok := models[modelID]
	return meta, ok
}

func KnownMetadataProviders() []string {
	providers := make([]string, 0, len(modelMetadata))
	for p := range modelMetadata {
		providers = append(providers, p)
	}
	sort.Strings(providers)
	return providers
}

var modelMetadata = map[string]map[string]ModelMetadata{
	"anthropic": {
		"claude-haiku-4-5-20251001": {
			DisplayName:     "Claude Haiku 4.5",
			Description:     "The fastest Claude model with near-frontier intelligence, optimized for speed and efficiency with strong reasoning capabilities.",
			ReleaseDate:     "2025-10",
			ContextWindow:   200000,
			MaxOutputTokens: 64000,
		},
		"claude-opus-4-6": {
			DisplayName:     "Claude Opus 4.6",
			Description:     "The most intelligent Claude model, designed for building agents and complex coding tasks with exceptional reasoning and long-context handling.",
			ReleaseDate:     "2025-12",
			ContextWindow:   1000000,
			MaxOutputTokens: 128000,
		},
		"claude-sonnet-4-6": {
			DisplayName:     "Claude Sonnet 4.6",
			Description:     "The best combination of speed and intelligence, offering rapid responses with competitive reasoning and coding capabilities.",
			ReleaseDate:     "2025-08",
			ContextWindow:   1000000,
			MaxOutputTokens: 64000,
		},
	},
	"gemini": {
		"gemini-2.5-flash": {
			DisplayName:     "Gemini 2.5 Flash",
			Description:     "Best-in-class thinking model with 1M context, excelling at complex reasoning tasks with significantly improved response quality.",
			ReleaseDate:     "2025-05",
			ContextWindow:   1048576,
			MaxOutputTokens: 65536,
		},
		"gemini-2.5-flash-lite": {
			DisplayName:     "Gemini 2.5 Flash Lite",
			Description:     "Cost-efficient Gemini 2.5 variant with 1M context, optimized for large-scale deployment with strong reasoning at reduced cost.",
			ReleaseDate:     "2025-06",
			ContextWindow:   1048576,
			MaxOutputTokens: 65536,
		},
		"gemini-2.5-pro": {
			DisplayName:     "Gemini 2.5 Pro",
			Description:     "Most capable Gemini 2.5 model with 1M context, excelling at complex reasoning, coding, and multimodal understanding tasks.",
			ReleaseDate:     "2025-03",
			ContextWindow:   1048576,
			MaxOutputTokens: 65536,
		},
	},
	"lmstudio": {},
	"mistral": {
		"magistral-medium-2509": {
			DisplayName:     "Magistral Medium 1.2",
			Description:     "Advanced reasoning model with frontier-class performance supporting function-calling, document QnA, chat completions, and batching.",
			ReleaseDate:     "2025-09",
			ContextWindow:   128000,
			MaxOutputTokens: 40960,
		},
		"magistral-small-2509": {
			DisplayName:     "Magistral Small 1.2",
			Description:     "Efficient reasoning model providing advanced problem-solving capabilities with optimized performance for resource-constrained deployments.",
			ReleaseDate:     "2025-09",
			ContextWindow:   128000,
			MaxOutputTokens: 40960,
		},
		"ministral-14b-2512": {
			DisplayName:     "Ministral 3 14B",
			Description:     "Largest model in the Ministral 3 family with 14B parameters, combining strong text and vision capabilities with efficient inference.",
			ReleaseDate:     "2025-12",
			ContextWindow:   256000,
			MaxOutputTokens: 65536,
		},
		"ministral-3b-2512": {
			DisplayName:     "Ministral 3 3B",
			Description:     "Compact 3B parameter model offering best-in-class text and vision capabilities for edge and lightweight deployments.",
			ReleaseDate:     "2025-12",
			ContextWindow:   256000,
			MaxOutputTokens: 65536,
		},
		"ministral-8b-2512": {
			DisplayName:     "Ministral 3 8B",
			Description:     "Efficient 8B parameter model with best-in-class text and vision capabilities for balanced performance and computational efficiency.",
			ReleaseDate:     "2025-12",
			ContextWindow:   256000,
			MaxOutputTokens: 65536,
		},
		"mistral-large-2512": {
			DisplayName:     "Mistral Large 3",
			Description:     "State-of-the-art general-purpose multimodal model for high-complexity tasks requiring maximum reasoning capability.",
			ReleaseDate:     "2025-12",
			ContextWindow:   256000,
			MaxOutputTokens: 131072,
		},
		"mistral-medium-2508": {
			DisplayName:     "Mistral Medium 3.1",
			Description:     "Frontier-class multimodal model released August 2025 for advanced applications requiring sophisticated reasoning and multi-modal understanding.",
			ReleaseDate:     "2025-08",
			ContextWindow:   128000,
			MaxOutputTokens: 65536,
		},
		"mistral-small-2603": {
			DisplayName:     "Mistral Small 4",
			Description:     "March 2026 release of Mistral Small 4, a highly efficient hybrid model unifying instruction following, reasoning, and coding capabilities.",
			ReleaseDate:     "2026-03",
			ContextWindow:   256000,
			MaxOutputTokens: 65536,
		},
	},
	"openai": {
		"gpt-5.4-2026-03-05": {
			DisplayName:     "GPT-5.4",
			Description:     "Frontier model for complex professional work excelling in agentic, coding, and professional workflows with 1M context and variable reasoning.",
			ReleaseDate:     "2026-03",
			ContextWindow:   1050000,
			MaxOutputTokens: 128000,
		},
		"gpt-5.4-mini-2026-03-17": {
			DisplayName:     "GPT-5.4 Mini",
			Description:     "Fastest mini model for coding, computer use, and subagents — brings GPT-5.4 capabilities to high-volume workloads with 400K context.",
			ReleaseDate:     "2026-03",
			ContextWindow:   400000,
			MaxOutputTokens: 128000,
		},
		"gpt-5.4-nano-2026-03-17": {
			DisplayName:     "GPT-5.4 Nano",
			Description:     "Cheapest GPT-5.4-class model optimized for classification, data extraction, ranking, and sub-agents at scale.",
			ReleaseDate:     "2026-03",
			ContextWindow:   400000,
			MaxOutputTokens: 128000,
		},
		"gpt-5.4-pro-2026-03-05": {
			DisplayName:     "GPT-5.4 Pro",
			Description:     "Premium GPT-5.4 variant offering maximum capability for complex enterprise workloads at frontier performance.",
			ReleaseDate:     "2026-03",
			ContextWindow:   1050000,
			MaxOutputTokens: 128000,
		},
	},
}
