// Code generated by scripts/sync-model-registry. DO NOT EDIT.

package model

import "sort"

// ModelPricingSpec holds the cost rates for a specific model.
// All costs are expressed in USD per million tokens.
type ModelPricingSpec struct {
	// InputCostPerMillion is the cost charged per million input (prompt) tokens.
	InputCostPerMillion float64

	// OutputCostPerMillion is the cost charged per million output (completion) tokens.
	OutputCostPerMillion float64
}

// modelPricing maps provider → exact modelID → ModelPricingSpec.
// All costs are in USD per million tokens.
var modelPricing = map[string]map[string]ModelPricingSpec{
	"anthropic": {
		"claude-haiku-4-5-20251001": {InputCostPerMillion: 1.0, OutputCostPerMillion: 5.0},
		"claude-opus-4-6":           {InputCostPerMillion: 5.0, OutputCostPerMillion: 25.0},
		"claude-sonnet-4-6":         {InputCostPerMillion: 3.0, OutputCostPerMillion: 15.0},
	},
	"gemini": {
		"gemini-2.0-flash":                              {InputCostPerMillion: 0.1, OutputCostPerMillion: 0.7},
		"gemini-2.0-flash-lite":                         {InputCostPerMillion: 0.075, OutputCostPerMillion: 0.3},
		"gemini-2.5-computer-use-preview-10-2025":       {InputCostPerMillion: 1.25, OutputCostPerMillion: 2.5},
		"gemini-2.5-flash":                              {InputCostPerMillion: 0.3, OutputCostPerMillion: 2.5},
		"gemini-2.5-flash-image":                        {InputCostPerMillion: 0.3, OutputCostPerMillion: 0.03},
		"gemini-2.5-flash-lite":                         {InputCostPerMillion: 0.1, OutputCostPerMillion: 0.4},
		"gemini-2.5-flash-lite-preview-09-2025":         {InputCostPerMillion: 0.1, OutputCostPerMillion: 0.3},
		"gemini-2.5-flash-native-audio-preview-12-2025": {InputCostPerMillion: 0.5, OutputCostPerMillion: 3.0},
		"gemini-2.5-flash-preview-tts":                  {InputCostPerMillion: 0.5, OutputCostPerMillion: 10.0},
		"gemini-2.5-pro":                                {InputCostPerMillion: 2.5, OutputCostPerMillion: 15.0},
		"gemini-2.5-pro-preview-tts":                    {InputCostPerMillion: 1.0, OutputCostPerMillion: 20.0},
		"gemini-3-flash-preview":                        {InputCostPerMillion: 0.5, OutputCostPerMillion: 1.0},
		"gemini-3-pro-image-preview":                    {InputCostPerMillion: 2.0, OutputCostPerMillion: 0.0011},
		"gemini-3.1-flash-image-preview":                {InputCostPerMillion: 0.5, OutputCostPerMillion: 3.0},
		"gemini-3.1-flash-lite-preview":                 {InputCostPerMillion: 0.25, OutputCostPerMillion: 0.5},
		"gemini-3.1-pro-preview":                        {InputCostPerMillion: 2.0, OutputCostPerMillion: 4.0},
		"gemini-3.1-pro-preview-customtools":            {InputCostPerMillion: 2.0, OutputCostPerMillion: 4.0},
		"gemini-embedding-001":                          {InputCostPerMillion: 0.15, OutputCostPerMillion: 0.075},
		"gemini-embedding-2-preview":                    {InputCostPerMillion: 0.2, OutputCostPerMillion: 0.45},
		"gemini-robotics-er-1.5-preview":                {InputCostPerMillion: 0.3, OutputCostPerMillion: 1.0},
	},
	"mistral": {
		"magistral-medium-2509": {InputCostPerMillion: 2.0, OutputCostPerMillion: 5.0},
		"magistral-small-2509":  {InputCostPerMillion: 0.5, OutputCostPerMillion: 1.5},
		"ministral-8b-2512":     {InputCostPerMillion: 0.15, OutputCostPerMillion: 0.15},
		"mistral-large-2512":    {InputCostPerMillion: 0.5, OutputCostPerMillion: 1.5},
		"mistral-medium-2508":   {InputCostPerMillion: 0.4, OutputCostPerMillion: 2.0},
		"mistral-small-2506":    {InputCostPerMillion: 0.1, OutputCostPerMillion: 0.3},
	},
	"openai": {
		"gpt-3.5-0301":              {InputCostPerMillion: 1.5, OutputCostPerMillion: 2.0},
		"gpt-3.5-turbo":             {InputCostPerMillion: 0.5, OutputCostPerMillion: 1.5},
		"gpt-3.5-turbo-0125":        {InputCostPerMillion: 0.5, OutputCostPerMillion: 1.5},
		"gpt-3.5-turbo-0613":        {InputCostPerMillion: 1.5, OutputCostPerMillion: 2.0},
		"gpt-3.5-turbo-1106":        {InputCostPerMillion: 1.0, OutputCostPerMillion: 2.0},
		"gpt-3.5-turbo-16k-0613":    {InputCostPerMillion: 3.0, OutputCostPerMillion: 4.0},
		"gpt-3.5-turbo-instruct":    {InputCostPerMillion: 1.5, OutputCostPerMillion: 2.0},
		"gpt-4-0125-preview":        {InputCostPerMillion: 10.0, OutputCostPerMillion: 30.0},
		"gpt-4-0314":                {InputCostPerMillion: 30.0, OutputCostPerMillion: 60.0},
		"gpt-4-0613":                {InputCostPerMillion: 30.0, OutputCostPerMillion: 60.0},
		"gpt-4-1106-preview":        {InputCostPerMillion: 10.0, OutputCostPerMillion: 30.0},
		"gpt-4-1106-vision-preview": {InputCostPerMillion: 10.0, OutputCostPerMillion: 30.0},
		"gpt-4-32k":                 {InputCostPerMillion: 60.0, OutputCostPerMillion: 120.0},
		"gpt-4-turbo-2024-04-09":    {InputCostPerMillion: 10.0, OutputCostPerMillion: 30.0},
		"gpt-4o-mini-transcribe":    {InputCostPerMillion: 1.25, OutputCostPerMillion: 5.0},
		"gpt-4o-mini-tts":           {InputCostPerMillion: 0.6, OutputCostPerMillion: 0.0},
		"gpt-4o-transcribe":         {InputCostPerMillion: 2.5, OutputCostPerMillion: 10.0},
		"gpt-4o-transcribe-diarize": {InputCostPerMillion: 2.5, OutputCostPerMillion: 10.0},
		"gpt-5.4":                   {InputCostPerMillion: 2.5, OutputCostPerMillion: 15.0},
		"gpt-5.4-pro":               {InputCostPerMillion: 30.0, OutputCostPerMillion: 180.0},
		"gpt-audio-1.5":             {InputCostPerMillion: 32.0, OutputCostPerMillion: 64.0},
		"gpt-image-1-mini":          {InputCostPerMillion: 2.5, OutputCostPerMillion: 8.0},
		"gpt-image-1.5":             {InputCostPerMillion: 8.0, OutputCostPerMillion: 32.0},
		"gpt-realtime-1.5":          {InputCostPerMillion: 32.0, OutputCostPerMillion: 64.0},
		"gpt-realtime-mini":         {InputCostPerMillion: 10.0, OutputCostPerMillion: 20.0},
	},
}

// GetModelPricing returns the pricing spec for an exact provider/modelID combination.
func GetModelPricing(provider, modelID string) (ModelPricingSpec, bool) {
	models, ok := modelPricing[provider]
	if !ok {
		return ModelPricingSpec{}, false
	}
	spec, ok := models[modelID]
	return spec, ok
}

// KnownPricingProviders returns providers that have pricing entries, sorted alphabetically.
func KnownPricingProviders() []string {
	providers := make([]string, 0, len(modelPricing))
	for p := range modelPricing {
		providers = append(providers, p)
	}
	sort.Strings(providers)
	return providers
}
