// Code generated by scripts/sync-model-registry. DO NOT EDIT.

package model

import "sort"

type ProviderSpec struct {
	ID          string
	DisplayName string
	BaseURL     string
	DocsURL     string
	PricingURL  string
}

func GetProvider(id string) (ProviderSpec, bool) {
	spec, ok := providerSpecs[id]
	return spec, ok
}

func AllProviders() []ProviderSpec {
	ids := KnownProviders()
	out := make([]ProviderSpec, 0, len(ids))
	for _, id := range ids {
		out = append(out, providerSpecs[id])
	}
	return out
}

func KnownProviders() []string {
	ids := make([]string, 0, len(providerSpecs))
	for id := range providerSpecs {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

func OfficialProviderModelDocsURL(provider string) (string, bool) {
	spec, ok := providerSpecs[provider]
	if !ok || spec.DocsURL == "" {
		return "", false
	}
	return spec.DocsURL, true
}

func OfficialProviderPricingURL(provider string) (string, bool) {
	spec, ok := providerSpecs[provider]
	if !ok || spec.PricingURL == "" {
		return "", false
	}
	return spec.PricingURL, true
}

var providerSpecs = map[string]ProviderSpec{
	"anthropic": {
		ID:          "anthropic",
		DisplayName: "Anthropic Claude",
		BaseURL:     "https://api.anthropic.com",
		DocsURL:     "https://docs.anthropic.com/en/docs/about-claude/models",
		PricingURL:  "https://anthropic.com/pricing",
	},
	"gemini": {
		ID:          "gemini",
		DisplayName: "Google Gemini",
		BaseURL:     "https://generativelanguage.googleapis.com",
		DocsURL:     "https://ai.google.dev/gemini-api/docs/models",
		PricingURL:  "https://ai.google.dev/gemini-api/docs/pricing",
	},
	"lmstudio": {
		ID:          "lmstudio",
		DisplayName: "LM Studio",
		BaseURL:     "http://localhost:1234/v1",
		DocsURL:     "https://lmstudio.ai/docs",
		PricingURL:  "",
	},
	"mistral": {
		ID:          "mistral",
		DisplayName: "Mistral AI",
		BaseURL:     "https://api.mistral.ai",
		DocsURL:     "https://docs.mistral.ai/getting-started/models/models_overview/",
		PricingURL:  "https://mistral.ai/pricing",
	},
	"openai": {
		ID:          "openai",
		DisplayName: "OpenAI",
		BaseURL:     "https://api.openai.com",
		DocsURL:     "https://developers.openai.com/api/docs/models",
		PricingURL:  "https://developers.openai.com/api/docs/pricing",
	},
}
